spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost:3306/likelion-db;MODE=MYSQL
    username: root
    password: 12345678
    hikari:
      jdbc-url: jdbc:h2:mem://localhost:3306/likelion-db;MODE=MYSQL
  h2:
    console:
      enabled: true
      path=/h2:
      logging:
  level:
    root: info
  jpa:
    properties:
      hibernate:
        dialect = org.hibernate.dialect.MySQL5InnoDBDialect
        dialect.storage_engine = innodb
    show-sql: true





