spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/likelion-db
    username: root
    password: 12345678

logging:
  level:
    root: info

spring.datasource.url: jdbc:h2:mem:likelion-db
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: root
spring.datasource.password: 12345678
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect